name: "Upcoming Conference"
description: "Open an issue for an upcoming talk, meetup, or conference"
title: "[CONFERENCE]: [TALK NAME], (Day, Month, Year)"
labels: [Developer-Community]
assignees:
  - mishmanners
body:
  - type: markdown
    attributes:
      value: |
        Add in the name of the conference, talk, meetup, and the title of the talk
  - type: input
    id: title
    attributes:
      label: Title of talk
      description: "What is the title of the talk?"
    validations:
      required: true
  - type: textarea
    id: talk
    attributes:
      label: Abstract 
      description: "What is the talk abstract?"
    validations:
      required: true
  - type: dropdown
    id: Type
    attributes:
      label: Event type
      description: "What kind of event is this?"
      options:
        - Conference
        - Meetup or User group
        - Workshop
        - Hackathon
    validations:
      required: true
  - type: checkboxes
    id: products
    attributes:
      label: SSW Products
      description: "What SSW products are being showcased in this talk?"
      options:
        - label: SSW Rules
          required: false
        - label: TinaCMS
          required: false
        - label: YakShaver
          required: false
        - label: SSW Rewards
          required: false
        - label: SugarLearning
          required: false
  - type: checkboxes
    id: list
    attributes:
      label: Checklist for all conferences, talks, and meetups
      description: "Tick each off as you go"
      options:
        - label: Chat to Adam and Gert (pre-approval)
          required: false
        - label: Approval for [remote working](https://my.sugarlearning.com/SSW/items/14116/training-conferences-self-education-and-software-licenses#2-process-for-attending-training-and-conferences) form
          required: false
        - label: If SSW present at event ask Penny to include talk on website
          required: false
        - label: Send email with all conference details to Gert, Adam, and Uly (include above three checkpoints). Content chooser event-attendance-request
          required: false
        - label: Book flights and accommodation
          required: false
        - label: International travel [exception](https://forms.office.com/pages/responsepage.aspx) form
          required: false
        - label: SSW Rewards app QR code
          required: false
        - label: Social media promo
          required: false
        - label: Post event report
          required: false
