name: "Upcoming Conference"
description: Open an issue for an upcoming talk, meetup, or conference
title: "[TALK NAME]: [CONFERENCE], (Day, Month, Year)"
labels: [Developer-Community, conference]
assignees:
  - mishmanners
body:
  - type: markdown
    attributes:
      value: |
        Add in the name of the conference, talk, meetup, and the title of the talk
  - type: input
    id: title
    attributes:
      label: title
      description: What is the title of the talk?
    validations:
      required: true
     
  - type: textarea
    id: talk
    attributes:
      label: abstract 
      description: What is the talk abstract?
    validations:
      required: true

  - type: dropdown
    id: Type
    attributes:
      label: style
      description: What kind of event is this?
      options:
        - Conference
        - Meetup or User group
        - Workshop
    validations:
      required: true

  - type: checkboxes
    id: products
    attributes:
      label: prods
      description: What SSW products are being showcased in this talk
      options:
        - label: SSW Rules
          required: false
        - label: TinaCMS
          required: false
        - label: YakShaver
 ▋
